# Numpy Tutorial

In [87]:
# Importing Library
import numpy as np

In [88]:
# Creating an Array in 1 Dimension and printing 
array_1d = np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [89]:
# verifying whether it is Numpy array or not
type(array_1d)

numpy.ndarray

In [90]:
# Knowing the dimension of the array
array_1d.ndim

1

In [91]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)
array_2d.ndim

[[1 2 3 4]
 [5 6 7 8]]


2

In [92]:
# Knowing the size of the data.
array_1d.size

4

In [93]:
array_2d.size

8

In [94]:
# Knowing the Rows and Columns of the data.
array_2d.shape

(2, 4)

In [95]:
# Knowing the type of the data
array_2d.dtype

dtype('int32')

In [96]:
matrix_Once = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_Once)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [97]:
# To auto create a huge matrix we have a funtion
# If we want to have a matrix with with values as 0 we use "zeros" and 'ones' for 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [98]:
mx_ones = np.ones((3,4))
print(mx_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [99]:
mx_Zeros = np.zeros((100,100))
print(mx_Zeros)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [100]:
mx = np.ones((3,4),dtype= int)
print(mx)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [101]:
mx_bool = np.zeros((4,6),dtype= bool)
print(mx_bool)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [102]:
# Using empty function will give random mix of numbers 
mx_empty = np.empty((3,3))
print(mx_empty)

[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


<!-- Numpy Functions -->

# Numpy Function
###  - arange()
###  - linespace()
###  - reshape()
###  - arange()
###  - ravel()
###  - flatten()
###  - transpose()

<!--  -->

In [103]:
array_1d = np.arange(1,13)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [104]:
array_odd = np.arange(1,13,2)
print(array_odd)

[ 1  3  5  7  9 11]


In [105]:
# Line space adds number of values in the given range.
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

In [106]:
array_2d = array_1d.reshape(3,4)
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [107]:
array_3d = array_1d.reshape(2,3,2)
print(array_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [108]:
array_new = np.arange(1,13).reshape(2,2,3)
print(array_new)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [109]:
# We use ravel function to convert any dimention array to 1d array
array_new.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [110]:
# 
array_new.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
# We can also use .T to transpose
array_new.transpose()

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])

In [112]:
array1 = np.arange(1,10).reshape(3,3)
array2 = np.arange(1,10).reshape(3,3)
print(array1)
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [113]:
a = array1 + array2
b = array1 - array2
c = array1 / array2
d = array1 * array2
print(a)
print(b)
print(c)
print(d)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [114]:
a = np.add(array1, array2)
b = np.subtract(array1, array2)
c = np.divide(array1, array2)
d = np.multiply(array1, array2)
print(a)
print(b)
print(c)
print(d)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [115]:
a = array1 @ array2
b = array1.dot(array2)
print(a)
print(b)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [116]:
a = array1.max()  # To get the max value  
b = array1.argmax()  # To get the index of the max value
print(a)
print(b)

9
8


In [117]:
a = array1.min()  # To get the min value
b = array1.argmin() # To get the index of the min value
print(a)
print(b)

1
0


In [118]:
# to find the max value from each row [1] or column [0]
a = array1.max(axis= 0) # here we are finding max values of each column
b = array1.max(axis= 1) # here we are finding max values of each row
print(a)
print(b)


[7 8 9]
[3 6 9]


In [119]:
a = np.sum(array1) # Will give total of all elements in array 1
b = np.sum(array1,axis=0) # Will give total of each column
c = np.sum(array1,axis=1) # Will give total of each row
print(a)
print(b)
print(c)

45
[12 15 18]
[ 6 15 24]


In [120]:
a = np.mean(array1) # This will give the average of all the elemnts in the array
b = np.sqrt(array1) # This will give the Square root of each element in an array
print(a)
print(b)


5.0
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [121]:
a = np.std(array1) # Calculates Standard deviation
b = np.exp(array1) # Calculates Exponential of each element
c = np.log(array1) # Calculates logs of each element
d = np.log10(array1) # Calculates logs base 10 of each element
print(a)
print(b)
print(c)
print(d)

2.581988897471611
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]
 [0.84509804 0.90308999 0.95424251]]


Python NumPy Array Slicing:

In [122]:
mx = np.arange(1,101).reshape(10,10)
print(mx)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [123]:
mx[0,0]

1

In [124]:
mx[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [125]:
mx[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [126]:
mx[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [127]:
mx

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [128]:
mx[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [129]:
mx[:,1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [130]:
mx.itemsize

4

Python Numpy Array Concatination and Split

In [132]:
mx1 = np.arange(1,17).reshape(4,4)
mx2 = np.arange(17,33).reshape(4,4)
print(mx1)
print(mx2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]


In [133]:
np.concatenate((mx1,mx2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [134]:
np.concatenate((mx1,mx2),axis=1)

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [135]:
np.vstack((mx1,mx2))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [136]:
np.hstack((mx1,mx2))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [137]:
np.hstack((mx1,mx2,mx1))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

In [138]:
np.split(mx1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [140]:
np.split(mx1,2,axis=1)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16]])]

In [141]:
d1 = np.array([4,7,1,3,9])

In [142]:
np.split(d1, [1,3])

[array([4]), array([7, 1]), array([3, 9])]